### ISSUE TITLE
"new-app" uses centos templates by default

### ISSUE THREAD

**Issue by thoraxe** [openshift/training#131]
`osc new-app https://github.com/openshift/simple-openshift-sinatra-sti.git -o yaml` will generate the following YAML:

``` yaml
apiVersion: v1beta1
creationTimestamp: null
items:
- apiVersion: v1beta1
  containerPort: 8080
  creationTimestamp: null
  id: simple-openshift-sinatra
  kind: Service
  port: 8080
  portName: simple-openshift-sinatra-sti-tcp-8080
  ports:
  - containerPort: 8080
    name: simple-openshift-sinatra-sti-tcp-8080
    port: 8080
    protocol: TCP
  protocol: TCP
  selector:
    deploymentconfig: simple-openshift-sinatra-sti
- apiVersion: v1beta1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: simple-openshift-sinatra-sti
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1beta1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: simple-openshift-sinatra-sti
  parameters:
    output:
      to:
        name: simple-openshift-sinatra-sti
    source:
      git:
        uri: https://github.com/openshift/simple-openshift-sinatra-sti.git
      type: Git
    strategy:
      stiStrategy:
        builderImage: openshift/ruby-20-centos7
        clean: true
        image: openshift/ruby-20-centos7
      type: STI
  triggers:
  - github:
      secret: bvtxaMKm4ysaKcZrDr1F
    type: github
  - generic:
      secret: mFBjA2_8lqfRxT-SUF49
    type: generic
- apiVersion: v1beta1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: simple-openshift-sinatra-sti
  template:
    controllerTemplate:
      podTemplate:
        desiredState:
          manifest:
            containers:
            - capabilities: {}
              image: library/simple-openshift-sinatra-sti:latest
              imagePullPolicy: ""
              name: simple-openshift-sinatra-sti
              ports:
              - containerPort: 8080
                name: simple-openshift-sinatra-sti-tcp-8080
                protocol: TCP
              resources: {}
            id: ""
            restartPolicy: {}
            version: v1beta2
            volumes: null
        labels:
          deploymentconfig: simple-openshift-sinatra-sti
      replicaSelector:
        deploymentconfig: simple-openshift-sinatra-sti
      replicas: 1
    strategy:
      type: Recreate
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - simple-openshift-sinatra-sti
      from:
        name: simple-openshift-sinatra-sti
      lastTriggeredImage: ""
      tag: latest
    type: ImageChange
kind: List
```

The image chosen is `openshift/ruby-20-centos7`. While the Docker configuration defaults to adding `registry.access.redhat.com`, as far as I know, there is no matching image there.

@brenton @sdodson
